feat(init) initial commit
base development tools and repository settings added

diff --git a/tools/Makefile b/tools/Makefile
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -1,4 +1,4 @@
-# Determinate absolute path to repo direcory
+# Determinate absolute path to the repo directory
 REPO = $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../)
 
 # Set virtualenv directory param
@@ -7,6 +7,19 @@ PYTHON = $(VENV)/bin/python
 
 # Temporary files location
 TEMP := $(shell mktemp /tmp/jatszoter-bashrc.XXXXXX)
+
+enable:
+	@if [ ! -f "$(VENV)/bin/activate" ]; then \
+  		echo "ERROR: Unable to find virtual env!"; \
+  		echo "ERROR: Please do 'make install' before!"; \
+  		exit 1; \
+  	fi
+	@echo "Starting Jatszoter Developing Environment..."
+	@cat $(HOME)/.bashrc $(VENV)/bin/activate > $(TEMP)
+	@register-python-argcomplete cz >> $(TEMP)
+	@cat $(REPO)/tools/motd
+	@/usr/bin/env bash --init-file $(TEMP)
+	@rm -v $(TEMP)
 
 uninstall:
 	rm -vf $(REPO)/.git/hooks/pre-push
@@ -18,10 +31,3 @@ install: uninstall
 	$(PYTHON) -m pip install -r $(REPO)/tools/requirements.txt
 
 update: uninstall install
-
-enable:
-	@cat $(HOME)/.bashrc $(VENV)/bin/activate > $(TEMP)
-	@register-python-argcomplete cz >> $(TEMP)
-	@cat $(REPO)/tools/motd
-	@/usr/bin/env bash --init-file $(TEMP)
-	@rm -v $(TEMP)
